config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  root             'static_pages#home'
  get    'help'       => 'static_pages#help'
  get    'about'      => 'static_pages#about'
  get    'contact'    => 'static_pages#contact'
  get    'signup'     => 'users#new'
  get    'login'      => 'sessions#new'
  post   'login'      => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'
  get    'inbox'      => 'conversations#index'
  resources :users
  resources :documents
  resources :conversations

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills
  acts_as_messageable

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def mailboxer_email(object)
      nil
  end


  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @documents = @user.documents
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to RampDoc!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

            private

                def user_params
                  params.require(:user).permit(:name, :email, :password,
                  :password_confirmation, :tag_list)
                end

                # Before filters

                # Confirms a logged-in user.
                def logged_in_user
                  unless logged_in?
                    store_location
                    flash[:danger] = "Please log in."
                    redirect_to login_url
                  end
                end

                # Confirms the correct user.
                def correct_user
                  @user = User.find(params[:id])
                  redirect_to(root_url) unless @user == current_user
                end

                # Confirms the correct user.
                def correct_user
                  @user = User.find(params[:id])
                  redirect_to(root_url) unless current_user?(@user)
                end

                # Confirms an admin user.
                def admin_user
                  redirect_to(root_url) unless current_user.admin?
                end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "delete", user, method: :delete,
  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<img class="signup-image" width="100%" src="http://www.whitby-seafoods.com/images/background3.jpg">


<div class="signup-wrapper">
    <h1>Sign up</h1>

    <div class="row signup">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', :placeholder =>"Bob Smith" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', :placeholder =>"user@example.com" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', :placeholder =>"**********" %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control',:placeholder =>"**********" %>

        <%= f.label :skill_tags %>
        <%= f.text_field :tag_list, class: 'form-control', :placeholder => "FP&A, Accounting, HTML/CSS, ROR, etc."%>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container-fluid profile-wrapper">

    <div class="row">

        <div class="col-md-3 image-profile">
            <img class="img-circle" src="http://davemorrowphotography.smugmug.com/Bestof/Portfolio/i-9WfNDJx/8/XL/When%20Worlds%20Collide-XL.jpg" style="width:150px;height:150px">
        </div>

        <div class="col-md-5 profile-content">
            <h1><%= @user.name %></h1>
            <span>
                <%= link_to " ", {controller: 'conversations', action: 'new', user_id: @user.id}, :class => "glyphicon glyphicon-envelope" %>
            </span>
        </div>

        <div class="col-md-4 profile-tags">
            <p><strong>Skills:
                <% @user.tag_list.each do |t| %>
                <ul><span class="label label-warning"><%= t %></span></ul>
                <% end %>
                </strong>
            </p>
        </div>

    </div>
</div>


<div class="row profile-lower">
    <div class="col-md-4 notifications">
        <h3 class="glyphicon glyphicon-flash"></h3>
        <ul class="small-font">Coming Soon</ul>
    </div>

    <div class="col-md-4 created-docs">
        <h3 class="glyphicon glyphicon-cloud"></h3>
        <div class="document-list">
            <% @documents.each do |d| %>
            <ul><%= link_to d.title, document_path(d)%></ul>
            <% end %>
        </div>
    </div>

    <div class="col-sm-4 create-docs">
        <div>
            <h3 class="glyphicon glyphicon-cloud-upload"></h3>
            <div id="upload">
                <%= link_to "", new_document_path, class: "glyphicon glyphicon-plus-sign" %>
            </div>
        </div>
    </div>

</div>